import type { App, Component } from 'vue'
import {
  NAlert,
  NAutoComplete,
  NBadge,
  NButton,
  NButtonGroup,
  NCard,
  NCheckbox,
  NCode,
  NCollapse,
  NCollapseItem,
  NDataTable,
  NDescriptions,
  NDescriptionsItem,
  NDivider,
  NDrawer,
  NDrawerContent,
  NDropdown,
  NDynamicInput,
  NDynamicTags,
  NEmpty,
  NForm,
  NFormItem,
  NGi,
  NGrid,
  NGridItem,
  NIcon,
  NInput,
  NInputNumber,
  NLi,
  NList,
  NListItem,
  NModal,
  NPageHeader,
  NPopconfirm,
  NProgress,
  NRadio,
  NRadioButton,
  NRadioGroup,
  NResult,
  NScrollbar,
  NSelect,
  NSkeleton,
  NSlider,
  NSpace,
  NSpin,
  NSplit,
  NStatistic,
  NStep,
  NSteps,
  NSwitch,
  NTab,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NThing,
  NTimeline,
  NTimelineItem,
  NTooltip,
  NTree,
  NUl,
  NUpload,
} from 'naive-ui'

const components: Array<[string, Component]> = [
  ['n-alert', NAlert],
  ['n-auto-complete', NAutoComplete],
  ['n-badge', NBadge],
  ['n-button', NButton],
  ['n-button-group', NButtonGroup],
  ['n-card', NCard],
  ['n-checkbox', NCheckbox],
  ['n-code', NCode],
  ['n-collapse', NCollapse],
  ['n-collapse-item', NCollapseItem],
  ['n-data-table', NDataTable],
  ['n-descriptions', NDescriptions],
  ['n-descriptions-item', NDescriptionsItem],
  ['n-divider', NDivider],
  ['n-drawer', NDrawer],
  ['n-drawer-content', NDrawerContent],
  ['n-dropdown', NDropdown],
  ['n-dynamic-input', NDynamicInput],
  ['n-dynamic-tags', NDynamicTags],
  ['n-empty', NEmpty],
  ['n-form', NForm],
  ['n-form-item', NFormItem],
  ['n-gi', NGi],
  ['n-grid', NGrid],
  ['n-grid-item', NGridItem],
  ['n-icon', NIcon],
  ['n-input', NInput],
  ['n-input-number', NInputNumber],
  ['n-li', NLi],
  ['n-list', NList],
  ['n-list-item', NListItem],
  ['n-modal', NModal],
  ['n-page-header', NPageHeader],
  ['n-popconfirm', NPopconfirm],
  ['n-progress', NProgress],
  ['n-radio', NRadio],
  ['n-radio-button', NRadioButton],
  ['n-radio-group', NRadioGroup],
  ['n-result', NResult],
  ['n-scrollbar', NScrollbar],
  ['n-select', NSelect],
  ['n-skeleton', NSkeleton],
  ['n-slider', NSlider],
  ['n-space', NSpace],
  ['n-spin', NSpin],
  ['n-split', NSplit],
  ['n-statistic', NStatistic],
  ['n-step', NStep],
  ['n-steps', NSteps],
  ['n-switch', NSwitch],
  ['n-tab', NTab],
  ['n-tab-pane', NTabPane],
  ['n-tabs', NTabs],
  ['n-tag', NTag],
  ['n-text', NText],
  ['n-thing', NThing],
  ['n-timeline', NTimeline],
  ['n-timeline-item', NTimelineItem],
  ['n-tooltip', NTooltip],
  ['n-tree', NTree],
  ['n-ul', NUl],
  ['n-upload', NUpload],
]

export default function installNaiveComponents(app: App) {
  for (const [name, component] of components) {
    app.component(name, component)
  }
}
